// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadAndLaunchUpdater():Promise<void>;

export function GetDisplayVisibility():Promise<boolean>;

export function GetSettings():Promise<string>;

export function GetSettingsAutoUpdate():Promise<boolean>;

export function GetSettingsVisibility():Promise<boolean>;

export function LoadSettings():Promise<void>;

export function OnFileDrop(arg1:Array<string>):Promise<void>;

export function OnGeoJSONFileDropped(arg1:Array<any>):Promise<void>;

export function SaveSettings(arg1:string):Promise<void>;

export function Shutdown():Promise<void>;
