// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDisplayVisibility():Promise<boolean>;

export function GetSettings():Promise<string>;

export function GetSettingsVisibility():Promise<boolean>;

export function LoadSettings():Promise<void>;

export function SaveSettings(arg1:string):Promise<void>;
