// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDisplayVisibility() {
  return window['go']['main']['App']['GetDisplayVisibility']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSettingsVisibility() {
  return window['go']['main']['App']['GetSettingsVisibility']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function OnFileDrop(arg1) {
  return window['go']['main']['App']['OnFileDrop'](arg1);
}

export function OnGeoJSONFileDropped(arg1) {
  return window['go']['main']['App']['OnGeoJSONFileDropped'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
